apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
    - port: 10113
      protocol: TCP
      targetPort: 10113
  selector:
    app: api-gateway
  type: LoadBalancer
  loadBalancerIP: "34.75.93.162"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: eu.gcr.io/dse20-group-group-02/api-gateway
          imagePullPolicy: Always
          name: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: actor-registry-service
  name: actor-registry-service
spec:
  ports:
    - port: 40001
      protocol: TCP
      targetPort: 40001
  selector:
    app: actor-registry-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: actor-registry-service
  name: actor-registry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor-registry-service
  template:
    metadata:
      labels:
        app: actor-registry-service
    spec:
      containers:
        - image: eu.gcr.io/dse20-group-group-02/actor-registry-service
          imagePullPolicy: Always
          name: actor-registry-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-tracking-service
  name: status-tracking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-tracking-service
  template:
    metadata:
      labels:
        app: status-tracking-service
    spec:
      containers:
        - image: eu.gcr.io/dse20-group-group-02/status-tracking-service
          imagePullPolicy: Always
          name: status-tracking-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: actor-control-service
  name: actor-control-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor-control-service
  template:
    metadata:
      labels:
        app: actor-control-service
    spec:
      containers:
        - image: eu.gcr.io/dse20-group-group-02/actor-control-service
          imagePullPolicy: Always
          name: actor-control-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: actor-simulator
  name: actor-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor-simulator
  template:
    metadata:
      labels:
        app: actor-simulator
    spec:
      containers:
        - image: eu.gcr.io/dse20-group-group-02/actor-simulator
          imagePullPolicy: Always
          name: actor-simulator
